name: Daily PubMed Notification
on:
  schedule:
    - cron: '15 21 * * *' # # 매일 한국 시간 오전 6:15 시 (UTC 0시) 실행
  workflow_dispatch: # 직접 실행해볼 수 있는 버튼 생성

jobs:
  run_bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with: {python-version: '3.9'}
      - name: Install Libs
        run: pip install biopython openai
      - name: Run Script
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python main.py
